export const mockedOrderItem = {
  applied_discounts: [],
  base_cost_price: '0.0000',
  base_price: '34.9500',
  base_total: '34.9500',
  base_wrapping_cost: '0.0000',
  bin_picking_number: '',
  configurable_fields: [],
  cost_price_ex_tax: '0.0000',
  cost_price_inc_tax: '0.0000',
  cost_price_tax: '0.0000',
  depth: '0.0000',
  ebay_item_id: '',
  ebay_transaction_id: '',
  event_date: '',
  event_name: null,
  external_id: null,
  fixed_shipping_cost: '0.0000',
  fulfillment_source: '',
  height: '0.0000',
  id: 43,
  is_bundled_product: false,
  is_refunded: false,
  name: '[Sample] Oak Cheese Grater',
  name_customer: '[Sample] Oak Cheese Grater',
  name_merchant: '[Sample] Oak Cheese Grater',
  option_set_id: null,
  order_address_id: 28,
  order_id: 127,
  parent_order_product_id: null,
  price_ex_tax: '34.9500',
  price_inc_tax: '34.9500',
  price_tax: '0.0000',
  product_id: 94,
  product_options: [
    {
      id: 85,
      option_id: 37,
      order_product_id: 89,
      product_option_id: 111,
      display_name: 'Color',
      display_name_customer: 'Color',
      display_name_merchant: 'Color',
      display_value: 'Silver',
      display_value_customer: 'Silver',
      display_value_merchant: 'Silver',
      value: '110',
      type: 'Swatch',
      name: 'Color1640255434-93',
      display_style: ''
    },
    {
      id: 86,
      option_id: 38,
      order_product_id: 89,
      product_option_id: 112,
      display_name: 'Size',
      display_name_customer: 'Size',
      display_name_merchant: 'Size',
      display_value: 'Small',
      display_value_customer: 'Small',
      display_value_merchant: 'Small',
      value: '114',
      type: 'Multiple choice',
      name: 'Size1640255337-93',
      display_style: 'Rectangle'
    }
  ],
  quantity: 1,
  quantity_refunded: 0,
  quantity_shipped: 0,
  refund_amount: '0.0000',
  return_id: 0,
  sku: 'OCG',
  total_ex_tax: '34.9500',
  total_inc_tax: '34.9500',
  total_tax: '0.0000',
  type: 'physical',
  upc: '',
  variant_id: 68,
  weight: '1.0000',
  width: '0.0000',
  wrapping_cost_ex_tax: '0.0000',
  wrapping_cost_inc_tax: '0.0000',
  wrapping_cost_tax: '0.0000',
  wrapping_message: '',
  wrapping_name: ''
};
