export const mockedOrder = {
  base_handling_cost: '0.0000',
  base_shipping_cost: '0.0000',
  base_wrapping_cost: '0.0000',
  billing_address: {
    city: 'O\'Keefeborough',
    company: 'Prohaska Inc',
    country: 'Poland',
    country_iso2: 'PL',
    email: 'stan@che.com',
    first_name: 'Fritz',
    form_fields: [
      {
        name: 'Type',
        value: ''
      }
    ],
    last_name: 'Jacobs',
    phone: '642-001-5244',
    state: '95957 Frederique Motorway',
    street_1: '4854 Boehm Groves',
    street_2: '2160 Zboncak Drives',
    zip: '172 Tiffany Coves'
  },
  cart_id: '8f0fbf8b-aac5-4734-b8fc-7c3d457acdb7',
  channel_id: 871856,
  coupon_discount: '0.0000',
  coupons: {
    resource: '/orders/127/coupons',
    url: 'https://api.bigcommerce.com/stores/moq5tdn0k6/v2/orders/127/coupons'
  },
  credit_card_type: null,
  currency_code: 'PLN',
  currency_exchange_rate: '1.0000000000',
  currency_id: 1,
  custom_status: 'Incomplete',
  customer_id: 0,
  customer_locale: 'en',
  customer_message: 'Et veniam saepe quisquam sapiente vel repudiandae dolor.',
  date_created: 'Tue, 11 Jan 2022 12:01:04 +0000',
  date_modified: 'Tue, 11 Jan 2022 12:01:44 +0000',
  date_shipped: '',
  default_currency_code: 'PLN',
  default_currency_id: 1,
  discount_amount: '0.0000',
  ebay_order_id: '0',
  external_id: null,
  external_merchant_id: null,
  external_source: '',
  geoip_country: 'Hungary',
  geoip_country_iso2: 'HU',
  gift_certificate_amount: '0.0000',
  handling_cost_ex_tax: '0.0000',
  handling_cost_inc_tax: '0.0000',
  handling_cost_tax: '0.0000',
  handling_cost_tax_class_id: 2,
  id: 127,
  ip_address: '176.63.28.150',
  ip_address_v6: '',
  is_deleted: true,
  is_email_opt_in: false,
  items_shipped: 0,
  items_total: 1,
  order_is_digital: false,
  order_source: 'vue',
  payment_method: 'Test Payment Gateway',
  payment_provider_id: null,
  payment_status: '',
  products: {
    resource: '/orders/127/products',
    url: 'https://api.bigcommerce.com/stores/moq5tdn0k6/v2/orders/127/products'
  },
  refunded_amount: '0.0000',
  shipping_address_count: 1,
  shipping_addresses: {
    resource: '/orders/127/shipping_addresses',
    url:
      'https://api.bigcommerce.com/stores/moq5tdn0k6/v2/orders/127/shipping_addresses'
  },
  shipping_cost_ex_tax: '0.0000',
  shipping_cost_inc_tax: '0.0000',
  shipping_cost_tax: '0.0000',
  shipping_cost_tax_class_id: 2,
  staff_notes: '',
  status: 'Incomplete',
  status_id: 0,
  store_credit_amount: '0.0000',
  store_default_currency_code: 'PLN',
  store_default_to_transactional_exchange_rate: '1.0000000000',
  subtotal_ex_tax: '34.9500',
  subtotal_inc_tax: '34.9500',
  subtotal_tax: '0.0000',
  tax_provider_id: 'BasicTaxProvider',
  total_ex_tax: '34.9500',
  total_inc_tax: '34.9500',
  total_tax: '0.0000',
  wrapping_cost_ex_tax: '0.0000',
  wrapping_cost_inc_tax: '0.0000',
  wrapping_cost_tax: '0.0000',
  wrapping_cost_tax_class_id: 3
};
